pipeline {
    agent {
        docker {
            image 'docker:28.5.1' 
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        DOCKERHUB_USER = "derrikjerry"
        IMAGE_NAME = "testapp3"
        IMAGE_TAG = "latest"
    }
    stages {
        stage('Install Python & Dependencies') {
            agent {
                docker {
                    image 'python:3.9'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh """
                    echo "Installing dependencies..."
                    sh 'python -m venv venv'
                    sh '. venv/bin/activate && pip install -r projects/webapp/requirements.txt'
                """
            }
        }

       

        stage('Build Docker Image') {
            steps {
                sh """
                    echo "Building Docker Image..."
                    docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG .
                """
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-cred',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh """
                        echo $PASS | docker login -u $USER --password-stdin
                    """
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                sh """
                    echo "Pushing image..."
                    docker push $DOCKERHUB_USER/$IMAGE_NAME:$IMAGE_TAG
                """
            }
        }
    }

    post {
        success { echo "CI Passed" }
        failure { echo "CI Failed" }
    }
}

